# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: weyna3939
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: eiei
# "service" is the name of this project. This will also be added to your AWS resource names.
service: project1

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
